name: Build

on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          path: ir-tool
          submodules: recursive

      - name: Initialize
        working-directory: ir-tool
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build firmware
        working-directory: ir-tool
        run: |
          west build -b adafruit_feather_m0_basic_proto app
